name: Docker Image CI
##
on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    name: build job
    steps:
      - name: Set up docker QEMU
        uses: docker/setup-qemu-action@v2
      
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      
      - name: Build and push
        uses: docker/build-push-action@v3
        with:
          context: "{{defaultContext}}:studentapp-main"
          push: true
          tags: tony06/student-app:latest
###
